[package]
name = "efisnake"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
uefi = { version = "0.36", features = ["logger", "panic_handler"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"